# Inspiración: https://github.com/marketplace/actions/latex-compilation

name: "Build LaTeX"

on:
  push:
    paths:
      - '**.tex'


jobs:
  build-latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build LaTex
        working-directory: ./doc
        run: make 